name: Deploy xneek-gpx lib to npm

on:
  push:
    branches: ["master"]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install
        run: yarn

      - name: build
        run: yarn build

      - name: minify
        run: yarn minify

      - name: Prepare NPM
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" >> ./.npmrc

      - name: Publish npm package
        run: npm publish --access public